/** @format */

export default [
  {
    id: "Zzp3GR4",
    title: "Going...down?",
    description: null,
    datetime: 1646491779,
    cover: "OBEUQxh",
    cover_width: 585,
    cover_height: 602,
    account_url: "ADegenFromUpcountry",
    account_id: 4294418,
    privacy: "hidden",
    layout: "blog",
    views: 119935,
    link: "https://imgur.com/a/Zzp3GR4",
    ups: 2082,
    downs: 16,
    points: 2066,
    score: 2125,
    is_album: true,
    vote: null,
    favorite: false,
    nsfw: false,
    section: "",
    comment_count: 238,
    favorite_count: 252,
    topic: null,
    topic_id: null,
    images_count: 1,
    in_gallery: true,
    is_ad: false,
    tags: [
      {
        name: "fuckputin",
        display_name: "fuckputin",
        followers: 467,
        total_items: 861,
        following: false,
        is_whitelisted: false,
        background_hash: "YDS5rp4",
        thumbnail_hash: null,
        accent: "24565E",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "fuckrussia",
        display_name: "fuckrussia",
        followers: 38,
        total_items: 51,
        following: false,
        is_whitelisted: false,
        background_hash: "5uFU9FR",
        thumbnail_hash: null,
        accent: "B85E44",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "slava_ukraini",
        display_name: "slava ukraini",
        followers: 144,
        total_items: 270,
        following: false,
        is_whitelisted: false,
        background_hash: "GEpMqov",
        thumbnail_hash: null,
        accent: "1E5F43",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "current_events",
        display_name: "current events",
        followers: 1225915,
        total_items: 365147,
        following: false,
        is_whitelisted: false,
        background_hash: "kQFyoG7",
        thumbnail_hash: null,
        accent: "699AAF",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "world news and events",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "ukraine",
        display_name: "ukraine",
        followers: 2915,
        total_items: 5496,
        following: false,
        is_whitelisted: false,
        background_hash: "OHK1wWY",
        thumbnail_hash: null,
        accent: "24565E",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
    ],
    ad_type: 0,
    ad_url: "",
    in_most_viral: true,
    include_album_ads: false,
    images: [
      {
        id: "OBEUQxh",
        title: null,
        description:
          "Maybe use the stairs next time?\n\nSauce: https://twitter.com/CarloPaski/status/1500039135431737344",
        datetime: 1646491696,
        type: "image/png",
        animated: false,
        width: 585,
        height: 602,
        size: 437707,
        views: 42787,
        bandwidth: 18728169409,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/OBEUQxh.png",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
    ],
    ad_config: {
      safeFlags: ["in_gallery", "sixth_mod_safe"],
      highRiskFlags: [],
      unsafeFlags: [],
      wallUnsafeFlags: [],
      showsAds: true,
    },
  },
  {
    id: "D0Umyw8",
    title: "How dare you question our authority",
    description: null,
    datetime: 1646491865,
    cover: "j6BXCCP",
    cover_width: 720,
    cover_height: 1042,
    account_url: "skapanda616",
    account_id: 13446541,
    privacy: "hidden",
    layout: "blog",
    views: 109238,
    link: "https://imgur.com/a/D0Umyw8",
    ups: 2210,
    downs: 29,
    points: 2181,
    score: 2235,
    is_album: true,
    vote: null,
    favorite: false,
    nsfw: false,
    section: "",
    comment_count: 225,
    favorite_count: 152,
    topic: null,
    topic_id: null,
    images_count: 2,
    in_gallery: true,
    is_ad: false,
    tags: [
      {
        name: "lgbt",
        display_name: "lgbt",
        followers: 3262,
        total_items: 2543,
        following: false,
        is_whitelisted: false,
        background_hash: "5uFU9FR",
        thumbnail_hash: null,
        accent: "B85E44",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "current_events",
        display_name: "current events",
        followers: 1225916,
        total_items: 365148,
        following: false,
        is_whitelisted: false,
        background_hash: "kQFyoG7",
        thumbnail_hash: null,
        accent: "699AAF",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "world news and events",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "fuckrondesantis",
        display_name: "fuckrondesantis",
        followers: 52,
        total_items: 81,
        following: false,
        is_whitelisted: false,
        background_hash: "1eQyuB1",
        thumbnail_hash: null,
        accent: "276860",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
    ],
    ad_type: 0,
    ad_url: "",
    in_most_viral: true,
    include_album_ads: false,
    images: [
      {
        id: "j6BXCCP",
        title: null,
        description: null,
        datetime: 1646491803,
        type: "image/png",
        animated: false,
        width: 720,
        height: 1042,
        size: 460339,
        views: 39003,
        bandwidth: 17954602017,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/j6BXCCP.png",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
      {
        id: "prdrZxY",
        title: null,
        description:
          "https://www.wfla.com/news/florida/florida-school-suspends-student-who-passed-out-pride-flags-at-dont-say-gay-walkout-report/\n\nhttps://www.change.org/p/rescind-jack-s-suspension",
        datetime: 1646491806,
        type: "image/png",
        animated: false,
        width: 720,
        height: 2646,
        size: 776203,
        views: 37494,
        bandwidth: 29102955282,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/prdrZxY.png",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
    ],
    ad_config: {
      safeFlags: ["album", "in_gallery", "sixth_mod_safe", "gallery"],
      highRiskFlags: [],
      unsafeFlags: [],
      wallUnsafeFlags: [],
      showsAds: true,
    },
  },
  {
    id: "NRcZJMb",
    title: "Must be banana bread",
    description: null,
    datetime: 1646483217,
    cover: "UWAiDXN",
    cover_width: 480,
    cover_height: 854,
    account_url: "PukeB",
    account_id: 3182423,
    privacy: "hidden",
    layout: "blog",
    views: 84835,
    link: "https://imgur.com/a/NRcZJMb",
    ups: 1129,
    downs: 16,
    points: 1113,
    score: 1155,
    is_album: true,
    vote: null,
    favorite: false,
    nsfw: false,
    section: "",
    comment_count: 39,
    favorite_count: 436,
    topic: null,
    topic_id: null,
    images_count: 1,
    in_gallery: true,
    is_ad: false,
    tags: [
      {
        name: "birds",
        display_name: "birds",
        followers: 22707,
        total_items: 18607,
        following: false,
        is_whitelisted: false,
        background_hash: "Z7iodQm",
        thumbnail_hash: null,
        accent: "225956",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "birbs",
        display_name: "birbs",
        followers: 6351,
        total_items: 3093,
        following: false,
        is_whitelisted: false,
        background_hash: "Z7iodQm",
        thumbnail_hash: null,
        accent: null,
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "cute",
        display_name: "cute",
        followers: 165950,
        total_items: 289204,
        following: false,
        is_whitelisted: false,
        background_hash: "MifWJps",
        thumbnail_hash: null,
        accent: "3BA3B1",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
    ],
    ad_type: 0,
    ad_url: "",
    in_most_viral: true,
    include_album_ads: false,
    images: [
      {
        id: "UWAiDXN",
        title: null,
        description: "Source: https://www.instagram.com/mrjeffthebird/",
        datetime: 1646482927,
        type: "video/mp4",
        animated: true,
        width: 480,
        height: 854,
        size: 2745557,
        views: 582129,
        bandwidth: 1598268350853,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: true,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/UWAiDXN.mp4",
        mp4_size: 2745557,
        mp4: "https://i.imgur.com/UWAiDXN.mp4",
        gifv: "https://i.imgur.com/UWAiDXN.gifv",
        hls: "https://i.imgur.com/UWAiDXN.m3u8",
        processing: {
          status: "completed",
        },
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
    ],
    ad_config: {
      safeFlags: ["album", "in_gallery", "sixth_mod_safe", "gallery"],
      highRiskFlags: [],
      unsafeFlags: [],
      wallUnsafeFlags: [],
      showsAds: true,
    },
  },
  {
    id: "fV4gYgS",
    title: "Hillbilly boy!",
    description: null,
    datetime: 1646490110,
    cover: "xepz3Ds",
    cover_width: 1200,
    cover_height: 1113,
    account_url: "SteveDaviss",
    account_id: 35884136,
    privacy: "hidden",
    layout: "blog",
    views: 98654,
    link: "https://imgur.com/a/fV4gYgS",
    ups: 990,
    downs: 41,
    points: 949,
    score: 998,
    is_album: true,
    vote: null,
    favorite: false,
    nsfw: false,
    section: "",
    comment_count: 77,
    favorite_count: 86,
    topic: null,
    topic_id: null,
    images_count: 1,
    in_gallery: true,
    is_ad: false,
    tags: [
      {
        name: "trending",
        display_name: "trending",
        followers: 810,
        total_items: 1013,
        following: false,
        is_whitelisted: false,
        background_hash: "Ikykl3U",
        thumbnail_hash: null,
        accent: "008261",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "meme",
        display_name: "meme",
        followers: 136924,
        total_items: 84978,
        following: false,
        is_whitelisted: false,
        background_hash: "1fDftsZ",
        thumbnail_hash: null,
        accent: "ba519f",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "funny",
        display_name: "funny",
        followers: 6226586,
        total_items: 2696993,
        following: false,
        is_whitelisted: false,
        background_hash: "9r1qCDq",
        thumbnail_hash: null,
        accent: "633875",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "LOLs, ROFLs, LMAOs",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "memes",
        display_name: "memes",
        followers: 2655799,
        total_items: 571229,
        following: false,
        is_whitelisted: false,
        background_hash: "1z4dgZT",
        thumbnail_hash: null,
        accent: "ba519f",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "the freshest memes",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
    ],
    ad_type: 0,
    ad_url: "",
    in_most_viral: true,
    include_album_ads: false,
    images: [
      {
        id: "xepz3Ds",
        title: null,
        description: null,
        datetime: 1646490074,
        type: "image/png",
        animated: false,
        width: 1200,
        height: 1113,
        size: 1193650,
        views: 37484,
        bandwidth: 44742776600,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/xepz3Ds.png",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
    ],
    ad_config: {
      safeFlags: ["album", "in_gallery", "sixth_mod_safe", "gallery"],
      highRiskFlags: [],
      unsafeFlags: [],
      wallUnsafeFlags: [],
      showsAds: true,
    },
  },
  {
    id: "EQYqwBi",
    title: "I have too many memes (vol. 81) - a daily dump",
    description: null,
    datetime: 1646490157,
    cover: "IiYvpvc",
    cover_width: 906,
    cover_height: 900,
    account_url: "MCKnowsTooManyFactsAboutBees",
    account_id: 131888315,
    privacy: "hidden",
    layout: "blog",
    views: 78830,
    link: "https://imgur.com/a/EQYqwBi",
    ups: 1030,
    downs: 40,
    points: 990,
    score: 1029,
    is_album: true,
    vote: null,
    favorite: false,
    nsfw: false,
    section: "",
    comment_count: 37,
    favorite_count: 133,
    topic: null,
    topic_id: null,
    images_count: 21,
    in_gallery: true,
    is_ad: false,
    tags: [
      {
        name: "memes",
        display_name: "memes",
        followers: 2655797,
        total_items: 571228,
        following: false,
        is_whitelisted: false,
        background_hash: "1z4dgZT",
        thumbnail_hash: null,
        accent: "ba519f",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "the freshest memes",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "meme_dump",
        display_name: "meme dump",
        followers: 69221,
        total_items: 27453,
        following: false,
        is_whitelisted: false,
        background_hash: "efV2eeb",
        thumbnail_hash: null,
        accent: null,
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "dump",
        display_name: "dump",
        followers: 92165,
        total_items: 56292,
        following: false,
        is_whitelisted: false,
        background_hash: "gbuk2AN",
        thumbnail_hash: null,
        accent: null,
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "random_shit",
        display_name: "random shit",
        followers: 802,
        total_items: 753,
        following: false,
        is_whitelisted: false,
        background_hash: "ILiOaNX",
        thumbnail_hash: null,
        accent: "4D549A",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
      {
        name: "dicksout",
        display_name: "dicksout",
        followers: 94,
        total_items: 115,
        following: false,
        is_whitelisted: false,
        background_hash: "CXErE2G",
        thumbnail_hash: null,
        accent: "5A3D74",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
    ],
    ad_type: 0,
    ad_url: "",
    in_most_viral: true,
    include_album_ads: false,
    images: [
      {
        id: "IiYvpvc",
        title: null,
        description: null,
        datetime: 1646489996,
        type: "image/jpeg",
        animated: false,
        width: 906,
        height: 900,
        size: 61071,
        views: 33646,
        bandwidth: 2054794866,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/IiYvpvc.jpg",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
      {
        id: "TTjQM57",
        title: null,
        description: null,
        datetime: 1646489998,
        type: "image/jpeg",
        animated: false,
        width: 828,
        height: 460,
        size: 31746,
        views: 32572,
        bandwidth: 1034030712,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/TTjQM57.jpg",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
      {
        id: "esV4gZf",
        title: null,
        description: null,
        datetime: 1646489999,
        type: "image/jpeg",
        animated: false,
        width: 900,
        height: 934,
        size: 61330,
        views: 31457,
        bandwidth: 1929257810,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/esV4gZf.jpg",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
    ],
    ad_config: {
      safeFlags: ["album", "in_gallery", "gallery"],
      highRiskFlags: [],
      unsafeFlags: ["sixth_mod_unsafe", "onsfw_mod_unsafe"],
      wallUnsafeFlags: [],
      showsAds: false,
    },
  },
  {
    id: "konmMJ3",
    title:
      "Admiral Kratch, a pyromaniac villain from a comic I'm working on. [OC]",
    description: null,
    datetime: 1646460088,
    cover: "sttLnwE",
    cover_width: 1600,
    cover_height: 3000,
    account_url: "DarkwoodArt",
    account_id: 40145249,
    privacy: "hidden",
    layout: "blog",
    views: 83141,
    link: "https://imgur.com/a/konmMJ3",
    ups: 751,
    downs: 28,
    points: 723,
    score: 764,
    is_album: true,
    vote: null,
    favorite: false,
    nsfw: false,
    section: "",
    comment_count: 51,
    favorite_count: 66,
    topic: null,
    topic_id: null,
    images_count: 1,
    in_gallery: true,
    is_ad: false,
    tags: [
      {
        name: "art",
        display_name: "art",
        followers: 1396976,
        total_items: 295929,
        following: false,
        is_whitelisted: false,
        background_hash: "07cWFIo",
        thumbnail_hash: null,
        accent: "9DCEC9",
        background_is_animated: false,
        thumbnail_is_animated: false,
        is_promoted: false,
        description: "creative creations",
        logo_hash: null,
        logo_destination_url: null,
        description_annotations: {},
      },
    ],
    ad_type: 0,
    ad_url: "",
    in_most_viral: true,
    include_album_ads: false,
    images: [
      {
        id: "sttLnwE",
        title: null,
        description:
          "Please let me know what you think/if you would like to see more. \nEdit: Thanks for the feedback everyone, this was more popular than I thought it would be. I'll be sure to post more art soon, and if anyone wants any commissions done for dnd characters/monsters/anything, message me or email me at jamesgkacinski@gmail.com, thanks for reading.",
        datetime: 1646459983,
        type: "image/jpeg",
        animated: false,
        width: 1600,
        height: 3000,
        size: 1199817,
        views: 30706,
        bandwidth: 36841580802,
        vote: null,
        favorite: false,
        nsfw: null,
        section: null,
        account_url: null,
        account_id: null,
        is_ad: false,
        in_most_viral: false,
        has_sound: false,
        tags: [],
        ad_type: 0,
        ad_url: "",
        edited: "0",
        in_gallery: false,
        link: "https://i.imgur.com/sttLnwE.jpg",
        comment_count: null,
        favorite_count: null,
        ups: null,
        downs: null,
        points: null,
        score: null,
      },
    ],
    ad_config: {
      safeFlags: ["album", "in_gallery", "sixth_mod_safe", "gallery"],
      highRiskFlags: [],
      unsafeFlags: [],
      wallUnsafeFlags: [],
      showsAds: true,
    },
  },
];
